// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZt98CIUYUBPeW32wvtA5hWOFlSLp03C0',
    appId: '1:281865054216:web:e2d79f491c1cc7d1',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    authDomain: 'ptw.firebaseapp.com',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    measurementId: 'G-9237PK55GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dLmiHHHoDBvJDySI3uZDVrXf-JdVTsE',
    appId: '1:281865054216:android:8575c8db8414e170f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVweah0fyrsmNbVnJtXkgl2dC6NBzOiA',
    appId: '1:281865054216:ios:8e0e40316f785630f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    iosClientId: '281865054216-eidk1u03c0j8nfudhttgki3kqh16vehm.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVweah0fyrsmNbVnJtXkgl2dC6NBzOiA',
    appId: '1:281865054216:ios:9b6804d79ab4c6f9f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    iosClientId: '281865054216-ut4ip07ghg3s803dq676h9sck6qao9j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopMemo.RunnerTests',
  );
}
