// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZt98CIUYUBPeW32wvtA5hWOFlSLp03C0',
    appId: '1:281865054216:web:b3a99ae715f22279f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    authDomain: 'ptw.firebaseapp.com',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    measurementId: 'G-VM27B0H9QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dLmiHHHoDBvJDySI3uZDVrXf-JdVTsE',
    appId: '1:281865054216:android:fe2c86110aabef18f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVweah0fyrsmNbVnJtXkgl2dC6NBzOiA',
    appId: '1:281865054216:ios:4bd05c96e30d4777f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    iosClientId: '281865054216-btk0ck7tcs5rgev0lbql01qoistr6bab.apps.googleusercontent.com',
    iosBundleId: 'ch.fritscher.snap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVweah0fyrsmNbVnJtXkgl2dC6NBzOiA',
    appId: '1:281865054216:ios:34ed6a8df15f2984f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    iosClientId: '281865054216-sgnrt0pp450pfth1qo5fnjdf5pv8li2u.apps.googleusercontent.com',
    iosBundleId: 'ch.fritscher.snap.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZt98CIUYUBPeW32wvtA5hWOFlSLp03C0',
    appId: '1:281865054216:web:b3a99ae715f22279f889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    authDomain: 'ptw.firebaseapp.com',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    measurementId: 'G-VM27B0H9QJ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDZt98CIUYUBPeW32wvtA5hWOFlSLp03C0',
    appId: '1:281865054216:web:b86e80dd1c10ed5df889bd',
    messagingSenderId: '281865054216',
    projectId: 'firebase-ptw',
    authDomain: 'ptw.firebaseapp.com',
    databaseURL: 'https://ptw.firebaseio.com',
    storageBucket: 'firebase-ptw.appspot.com',
    measurementId: 'G-HK1NQP05W7',
  );
}
